### PR TITLE
Update build-publish.yml

### LINKED ISSUE #40: Create authentication secrets for PyPi and Docker Hub
Per #38, automating new version publishing requires us to

- define Github secrets PYPI_USERNAME and PYPI_PASSWORD to access PyPI
- define Docker Hub authentication to publish to it
- Create an automation account on PyPi
- Create an automation account on Docker Hub - maybe `ha-mqtt-tooling`?

### PR DESCRIPTION
**Pull request by unixorn**
# Description

- Change username for pypi in `build-publish.yml` to `__token__`
- Add docker `username` and `password` to `build-publish.yml`

Closes #40 

# License Acceptance

- [x] This repository is Apache version 2.0 licensed (some scripts may have alternate licensing inline in their code) and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.

# Type of changes

- [ ] Add/update a helper script
- [ ] Add/update link to an external resource like a blog post or video
- [ ] Bug fix
- [ ] New feature
- [x] Test updates
- [ ] Text cleanups/updates

# Checklist

- [x] I have read the **CONTRIBUTING** document.
- [ ] All new and existing tests pass.
- [ ] Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is an allowed exception)
- [ ] Scripts added/updated in this PR are all marked executable.
- [ ] Scripts added/updated in this PR _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
- [ ] I have confirmed that any links added or updated in my PR are valid.

### CODE REVIEW

**Comment by unixorn** [comment]
@mion00 have a look at this please

**Comment by mion00** [comment]
Now it should work if you define the two secrets in Github.

**Comment by unixorn** [comment]
The docker login is better, thanks

**Comment by unixorn** [comment]
Releasing 0.6.0 to pypi worked like a charm because of this, thanks!

I'll have to figure out what I did wrong for hub.docker.com, though.

**Pull request merged**
