### PR TITLE
Improve Discoverable and BinarySensor classes

### LINKED ISSUE #13: [FEATURE] Add sensor instance to a device
**Is your feature request related to a problem? Please describe.**
Given an instance of a sensor, allow to pass it to a device, instead of using the current solution of `device.add_metric()` that requires re-defining again the sensor configuration in the `configuration` argument. 
 
**Describe the solution you'd like**
Add the ability to include directly the sensor instance when defining the _metrics_ of a device.
This could be useful to simplify the current code inside `add_metric()`: the configuration of the sensor is available directly from the passed sensor instance, instead of looking it up and having to parse the `configuration` dictionary

```python
sensor = BinarySensor()

device = Device()
device.add_sensor(sensor)
```

### PR DESCRIPTION
**Pull request by mion00**
# Description
The main changes in this PR are:
- A sensor can be associated to a device by populating its `device` field
- Add type parameter to the _Discoverable_ class so that each subclass manages a specific type of sensor
- Use `pydantic` to validate input settings and provide default values.
- Use `pytest` to run Python tests. Write some tests for _Discoverable_ and _BinarySensor_ classes (some of the tests require a local MQTT broker running).
- Update `README.md` with new instructions for creating a sensor and associating it to a device.
- Add `docker-compose.yml` to ease in local development and testing.

According to the [Home Assistant MQTT discovery protocol](https://www.home-assistant.io/integrations/binary_sensor.mqtt/#device), a sensor is linked to a device when it provides the `device` field in its configuration. I suggest we associate a sensor to a device in a similar manner. The current solution of using a `Device` object with its `add_metric` does not allow to re-use the existing `BinarySensor` class, or any additional sensor classes that will be added in the future.
This change brings the following advantages: 
- If a sensor instance is linked to a device, a user can update the sensor by directly invoking its methods, without having to call every time `add_metric()` and `publish()` on the `Device` object
- When a device contains multiple sensors, avoid iterating over all the sensors and publishing each state when a single sensor changes.
  - If the information about a device change (e.g. the software version), the user needs only to update a single instance of `DeviceInfo` and publish a state change on any of the linked sensors.

Fixes #13 (the `Device` class is no longer needed, since each `Sensor` now can be associated to a _device_)

If a `Device` class might be needed for convenience, it could be built simply as a wrapper around a _list_ of `sensor` instances, each of them pointing to the same `DeviceInfo` object.

# License Acceptance

- [x] This repository is Apache version 2.0 licensed (some scripts may have alternate licensing inline in their code) and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.

# Type of changes

- [ ] Add/update a helper script
- [ ] Add/update link to an external resource like a blog post or video
- [ ] Bug fix
- [x] New feature
- [x] Test updates
- [x] Text cleanups/updates

# Checklist

- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests pass.
- [ ] Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is an allowed exception)
- [ ] Scripts added/updated in this PR are all marked executable.
- [ ] Scripts added/updated in this PR _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
- [x] I have confirmed that any links added or updated in my PR are valid.

### CODE REVIEW

**Review by unixorn — APPROVED** [review]
This is a huge improvement, thank you very much.

**Comment by mion00** [comment]
Thank you for the initial groundwork! :wink: 
I have some doubts on how to integrate the CLI with these changes: have you considered an helper library for more easily defining and documenting the input parameters? I know `argparse` works, but it seems a bit cumbersome to define all the options inside the parser.
In the past I used the wonderful [Click](https://click.palletsprojects.com/en/8.1.x/) to write a simple CLI utility, but now I have been thinking about using [Typer](https://typer.tiangolo.com/), since it provides a more beautiful interface with less boilerplate annotations.

**Comment by unixorn** [comment]
Bump the version to 0.5.0 when you're ready to merge.

The command line tooling is currently charitably described as awkward. I mainly had it for testing, my initial thought had been to make this library as something people would pull into their own programs, but after using the cli scripts already in here, I realized that for a lot of users, something they can run from a shell prompt would make this far more usable. Let's discuss it more on https://github.com/unixorn/ha-mqtt-discovery/issues/18, I don't want to block merging your work on this PR

We can also address changing the argument handling in #18 . I'm not opposed to it, I used `argparse` to minimize the number of modules used that aren't included in the standard library. That said, they already have to pull in `pyaml`, `paho-mqtt` and others, so adding another one shouldn't be a deterrent if that makes argument handling easier for us.

**Comment by unixorn** [comment]
One tiny thing - please run `make format` to get poetry to run `black` on all the .py files. You can ignore the SPELL error in the megalint report, I just configured it to treat spell errors as warnings in https://github.com/unixorn/ha-mqtt-discovery/pull/16 to get it to stop complaining about `mosquitto` :-)

**Comment by mion00** [comment]
> One tiny thing - please run `make format` to get poetry to run `black` on all the .py files. You can ignore the SPELL error in the megalint report, I just configured it to treat spell errors as warnings in #16 to get it to stop complaining about `mosquitto` :-)

Yeah sorry I didn't quite know the workflow you followed in this repo. Tried to make sense of the Makefile but didn't know what targets were required before a commit.

**Comment by unixorn** [comment]
I added documentation for enabling the `git` hooks in https://github.com/unixorn/ha-mqtt-discovery/pull/19, but it boils down to running `hooks/autohook.sh install` from the top level of the repo. It'll automagically format during commit.

I'll document the Makefile better in another PR, sorry about that

**Comment by unixorn** [comment]
I'm going to defer working on #10 and #11 until after this PR lands. I don't want to make merge conflicts for you and the code change would need to be changed to work with this PR anyway

**Comment by unixorn** [comment]
This is a huge improvement, thank you very much for the contribution.

**Comment by mion00** [comment]
Happy to help! :+1:

**Pull request merged**
